twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form_theme/bootstrap_4_layout.html.twig'
        - 'form_theme/bootstrap_4_horizontal_layout.html.twig' # to be the default theme

when@test:
    twig:
        strict_variables: true
