parameters:
  # config from .env
  dotenv.ESA_TEAM_NAME: '%env(ESA_TEAM_NAME)%'
  dotenv.ESA_ACCESS_TOKEN: '%env(ESA_ACCESS_TOKEN)%'
  dotenv.ESA_WEBHOOK_SECRET: '%env(ESA_WEBHOOK_SECRET)%'
  dotenv.ESABA_PUBLIC_CATEGORIES: '%env(ESABA_PUBLIC_CATEGORIES)%'
  dotenv.ESABA_PUBLIC_TAGS: '%env(ESABA_PUBLIC_TAGS)%'
  dotenv.ESABA_PRIVATE_CATEGORIES: '%env(ESABA_PRIVATE_CATEGORIES)%'
  dotenv.ESABA_PRIVATE_TAGS: '%env(ESABA_PRIVATE_TAGS)%'
  dotenv.ESABA_HTML_REPLACEMENTS: '%env(ESABA_HTML_REPLACEMENTS)%'
  dotenv.ESABA_USER_ASSETS: '%env(ESABA_USER_ASSETS)%'
  dotenv.ESABA_ENABLE_INDEXING: '%env(ESABA_ENABLE_INDEXING)%'

  # config from config/esaba.php
  env(ESABA_PHP): '%kernel.project_dir%/config/esaba.php'
  env(ESABA_CONFIG): '%env(require:ESABA_PHP)%'
  env(PHP_ESA_TEAM_NAME): '%env(key:ESA_TEAM_NAME:json:ESABA_CONFIG)%'
  env(PHP_ESA_ACCESS_TOKEN): '%env(key:ESA_ACCESS_TOKEN:json:ESABA_CONFIG)%'
  env(PHP_ESA_WEBHOOK_SECRET): '%env(key:ESA_WEBHOOK_SECRET:json:ESABA_CONFIG)%'
  env(PHP_ESABA_PUBLIC_CATEGORIES): '%env(key:ESABA_PUBLIC_CATEGORIES:json:ESABA_CONFIG)%'
  env(PHP_ESABA_PUBLIC_TAGS): '%env(key:ESABA_PUBLIC_TAGS:json:ESABA_CONFIG)%'
  env(PHP_ESABA_PRIVATE_CATEGORIES): '%env(key:ESABA_PRIVATE_CATEGORIES:json:ESABA_CONFIG)%'
  env(PHP_ESABA_PRIVATE_TAGS): '%env(key:ESABA_PRIVATE_TAGS:json:ESABA_CONFIG)%'
  env(PHP_ESABA_HTML_REPLACEMENTS): '%env(key:ESABA_HTML_REPLACEMENTS:json:ESABA_CONFIG)%'
  env(PHP_ESABA_USER_ASSETS): '%env(key:ESABA_USER_ASSETS:json:ESABA_CONFIG)%'
  env(PHP_ESABA_ENABLE_INDEXING): '%env(key:ESABA_ENABLE_INDEXING:json:ESABA_CONFIG)%'

  # actual configs
  esa_team_name: '%env(string:default:dotenv.ESA_TEAM_NAME:PHP_ESA_TEAM_NAME)%'
  esa_access_token: '%env(string:default:dotenv.ESA_ACCESS_TOKEN:PHP_ESA_ACCESS_TOKEN)%'
  esa_webhook_secret: '%env(string:default:dotenv.ESA_WEBHOOK_SECRET:PHP_ESA_WEBHOOK_SECRET)%'
  esaba_public_categories: '%env(json:default:dotenv.ESABA_PUBLIC_CATEGORIES:PHP_ESABA_PUBLIC_CATEGORIES)%'
  esaba_public_tags: '%env(json:default:dotenv.ESABA_PUBLIC_TAGS:PHP_ESABA_PUBLIC_TAGS)%'
  esaba_private_categories: '%env(json:default:dotenv.ESABA_PRIVATE_CATEGORIES:PHP_ESABA_PRIVATE_CATEGORIES)%'
  esaba_private_tags: '%env(json:default:dotenv.ESABA_PRIVATE_TAGS:PHP_ESABA_PRIVATE_TAGS)%'
  esaba_html_replacements: '%env(json:default:dotenv.ESABA_HTML_REPLACEMENTS:PHP_ESABA_HTML_REPLACEMENTS)%'
  esaba_user_assets: '%env(json:default:dotenv.ESABA_USER_ASSETS:PHP_ESABA_USER_ASSETS)%'
  esaba_enable_indexing: '%env(bool:default:dotenv.ESABA_ENABLE_INDEXING:PHP_ESABA_ENABLE_INDEXING)%'
