parameters:
  # config from .env
  dotenv.ESA_TEAM_NAME: '%env(ESA_TEAM_NAME)%'
  dotenv.ESA_ACCESS_TOKEN: '%env(ESA_ACCESS_TOKEN)%'
  dotenv.ESA_WEBHOOK_SECRET: '%env(ESA_WEBHOOK_SECRET)%'
  dotenv.ESABA_PUBLIC_CATEGORIES: '%env(ESABA_PUBLIC_CATEGORIES)%'
  dotenv.ESABA_PUBLIC_TAGS: '%env(ESABA_PUBLIC_TAGS)%'
  dotenv.ESABA_PRIVATE_CATEGORIES: '%env(ESABA_PRIVATE_CATEGORIES)%'
  dotenv.ESABA_PRIVATE_TAGS: '%env(ESABA_PRIVATE_TAGS)%'
  dotenv.ESABA_HTML_REPLACEMENTS: '%env(ESABA_HTML_REPLACEMENTS)%'
  dotenv.ESABA_USER_ASSETS: '%env(ESABA_USER_ASSETS)%'

  # config from config/esaba.php
  env(ESABA_PHP): '%kernel.project_dir%/config/esaba.php'
  env(ESABA_CONFIG): '%env(require:ESABA_PHP)%'
  env(PHP_ESA_TEAM_NAME): '%env(key:ESA_TEAM_NAME:json:ESABA_CONFIG)%'
  env(PHP_ESA_ACCESS_TOKEN): '%env(key:ESA_ACCESS_TOKEN:json:ESABA_CONFIG)%'
  env(PHP_ESA_WEBHOOK_SECRET): '%env(key:ESA_WEBHOOK_SECRET:json:ESABA_CONFIG)%'
  env(PHP_ESABA_PUBLIC_CATEGORIES): '%env(key:ESABA_PUBLIC_CATEGORIES:json:ESABA_CONFIG)%'
  env(PHP_ESABA_PUBLIC_TAGS): '%env(key:ESABA_PUBLIC_TAGS:json:ESABA_CONFIG)%'
  env(PHP_ESABA_PRIVATE_CATEGORIES): '%env(key:ESABA_PRIVATE_CATEGORIES:json:ESABA_CONFIG)%'
  env(PHP_ESABA_PRIVATE_TAGS): '%env(key:ESABA_PRIVATE_TAGS:json:ESABA_CONFIG)%'
  env(PHP_ESABA_HTML_REPLACEMENTS): '%env(key:ESABA_HTML_REPLACEMENTS:json:ESABA_CONFIG)%'
  env(PHP_ESABA_USER_ASSETS): '%env(key:ESABA_USER_ASSETS:json:ESABA_CONFIG)%'

  # actual configs
  env(FINAL_ESA_TEAM_NAME): '%env(default:dotenv.ESA_TEAM_NAME:PHP_ESA_TEAM_NAME)%'
  env(FINAL_ESA_ACCESS_TOKEN): '%env(default:dotenv.ESA_ACCESS_TOKEN:PHP_ESA_ACCESS_TOKEN)%'
  env(FINAL_ESA_WEBHOOK_SECRET): '%env(default:dotenv.ESA_WEBHOOK_SECRET:PHP_ESA_WEBHOOK_SECRET)%'
  env(FINAL_ESABA_PUBLIC_CATEGORIES): '%env(default:dotenv.ESABA_PUBLIC_CATEGORIES:PHP_ESABA_PUBLIC_CATEGORIES)%'
  env(FINAL_ESABA_PUBLIC_TAGS): '%env(default:dotenv.ESABA_PUBLIC_TAGS:PHP_ESABA_PUBLIC_TAGS)%'
  env(FINAL_ESABA_PRIVATE_CATEGORIES): '%env(default:dotenv.ESABA_PRIVATE_CATEGORIES:PHP_ESABA_PRIVATE_CATEGORIES)%'
  env(FINAL_ESABA_PRIVATE_TAGS): '%env(default:dotenv.ESABA_PRIVATE_TAGS:PHP_ESABA_PRIVATE_TAGS)%'
  env(FINAL_ESABA_HTML_REPLACEMENTS): '%env(default:dotenv.ESABA_HTML_REPLACEMENTS:PHP_ESABA_HTML_REPLACEMENTS)%'
  env(FINAL_ESABA_USER_ASSETS): '%env(default:dotenv.ESABA_USER_ASSETS:PHP_ESABA_USER_ASSETS)%'
