# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration

imports:
  - { resource: esaba.yaml }

parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      string $teamName: '%env(string:FINAL_ESA_TEAM_NAME)%'
      array $htmlReplacements: '%env(json:FINAL_ESABA_HTML_REPLACEMENTS)%'

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  Symfony\Contracts\Cache\CacheInterface:
    class: Symfony\Component\Cache\Adapter\FilesystemAdapter
    arguments:
      $directory: '%kernel.project_dir%/var/cache/esa'

  Symfony\Component\DomCrawler\Crawler: ~

  Polidog\Esa\Api:
    factory: [Polidog\Esa\Api, factory]
    arguments:
      - '%env(string:FINAL_ESA_ACCESS_TOKEN)%'
      - '%env(string:FINAL_ESA_TEAM_NAME)%'

  App\Esa\WebhookValidator:
    arguments:
      - '%env(string:FINAL_ESA_WEBHOOK_SECRET)%'

  App\Service\AccessController:
    arguments:
      - '%env(json:FINAL_ESABA_PUBLIC_CATEGORIES)%'
      - '%env(json:FINAL_ESABA_PUBLIC_TAGS)%'
      - '%env(json:FINAL_ESABA_PRIVATE_CATEGORIES)%'
      - '%env(json:FINAL_ESABA_PRIVATE_TAGS)%'

  App\Service\AssetResolver:
    arguments:
      - '%env(json:FINAL_ESABA_USER_ASSETS)%'
