name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [8.0.2, 8.1]
        composer-install-options: ['', --prefer-lowest]

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ctype, dom, iconv

      - uses: actions/checkout@v2

      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Dependencies
        run: |
          composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist ${{ matrix.composer-install-options }}
          cp ./config/esa.yaml{.dist,}

      - name: Execute tests
        run: ./vendor/bin/phpunit --coverage-clover=coverage.clover

      - name: Send coverage file to Scrutinizer
        if: ${{ matrix.php-versions == '8.1' && matrix.composer-install-options == '' }}
        run: |
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.clover

      - name: PHP CS Fixer
        run: composer cs
